CREATE OR REPLACE TRIGGER trg_weekend_restrict BEFORE INSERT OR UPDATE OR DELETE ON EMPLOYEE
BEGIN
    -- IF UPPER(TRIM(TO_CHAR(SYSDATE, 'DAY', 'NLS_DATE_LANGUAGE=ENGLISH'))) IN ('SATURDAY','SUNDAY') THEN
    IF TO_CHAR(SYSDATE, 'DY') IN ('SAT','SUN') THEN
        RAISE_APPLICATION_ERROR(-20001,'You cannot use this table on Saturday and Sunday.');
    END IF;
END;
/

-- SET SERVEROUTPUT ON;
-- @ E:\BARAIYA_ANIL\ASSIGNMENT_4\Q1_Weekend_Restrict.sql

-- INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, JOB_TITLE, SALARY, DEPT_ID) VALUES (112, 'SAM', 'CLERK',2500, 10); 

-- CREATE TABLE EMPLOYEE
-- (
--     EMP_ID NUMBER(5) PRIMARY KEY,
--     EMP_NAME VARCHAR2(50) NOT NULL,
--     JOB_TITLE VARCHAR2(30),
--     SALARY NUMBER(8,2),
--     DEPT_ID NUMBER(4)
-- );
