CREATE OR REPLACE TRIGGER trg_check_itemno BEFORE INSERT ON ITEMS FOR EACH ROW
BEGIN
    IF UPPER(:NEW.ITEM_NO) NOT LIKE 'I%' THEN
        RAISE_APPLICATION_ERROR(-20002,'Item number must start with I or i.');
    END IF;
END;
/

-- SET SERVEROUTPUT ON;
-- @ E:\BARAIYA_ANIL\ASSIGNMENT_4\Q2_Check_ItemNo.sql

-- CREATE TABLE ITEMS (
--     ITEM_NO VARCHAR2(10) PRIMARY KEY,
--     ITEM_NAME VARCHAR2(30),
--     PRICE NUMBER(8,2)
-- );

-- Valide Commands

-- INSERT INTO ITEMS (ITEM_NO,ITEM_NAME,PRICE) VALUES ('I101', 'Mouse', 500);
-- INSERT INTO ITEMS (ITEM_NO,ITEM_NAME,PRICE) VALUES ('i102', 'Keyboard', 800);
-- INSERT INTO ITEMS (ITEM_NO,ITEM_NAME,PRICE) VALUES ('I103', 'Monitor', 1800);

-- InValide Commands

-- INSERT INTO ITEMS (ITEM_NO,ITEM_NAME,PRICE) VALUES ('A101', 'Mouse', 500);
-- INSERT INTO ITEMS (ITEM_NO,ITEM_NAME,PRICE) VALUES ('a102', 'Keyboard', 800);
-- INSERT INTO ITEMS (ITEM_NO,ITEM_NAME,PRICE) VALUES ('C103', 'Monitor', 1800);
