CREATE OR REPLACE TRIGGER trg_increase_passing_marks BEFORE UPDATE OF PASSING_MARKS ON SUBJECT FOR EACH ROW
BEGIN
    IF :NEW.PASSING_MARKS <= :OLD.PASSING_MARKS THEN
        RAISE_APPLICATION_ERROR(-20003,'Passing marks can only be increased, not decreased or kept same.');
    END IF;
END;
/

-- SET SERVEROUTPUT ON;
-- @ E:\BARAIYA_ANIL\ASSIGNMENT_4\Q3_Increase_Passing_Marks.sql

-- CREATE TABLE SUBJECT
-- (
--     SUB_ID NUMBER(4) PRIMARY KEY,
--     SUB_NAME VARCHAR2(40),
--     PASSING_MARKS NUMBER(3)
-- );

-- INSERT INTO SUBJECT (SUB_ID,SUB_NAME,PASSING_MARKS) VALUES (101, 'Mathematics', 35);
-- INSERT INTO SUBJECT (SUB_ID,SUB_NAME,PASSING_MARKS) VALUES (102, 'Science', 40);
-- INSERT INTO SUBJECT (SUB_ID,SUB_NAME,PASSING_MARKS) VALUES (103, 'English', 30);

-- Valide Commands

-- UPDATE SUBJECT SET PASSING_MARKS = 45 WHERE SUB_ID = 101;
-- UPDATE SUBJECT SET PASSING_MARKS = PASSING_MARKS + 5 WHERE SUB_ID = 101;

-- ✔ 35 → 45 (Increased → Allowed)

-- InValide Commands

-- UPDATE SUBJECT SET PASSING_MARKS = 25 WHERE SUB_ID = 103;
-- UPDATE SUBJECT SET PASSING_MARKS = PASSING_MARKS - 5 WHERE SUB_ID = 101;

--  ORA-20003: Passing marks can only be increased, not decreased or kept same.