CREATE OR REPLACE TRIGGER trg_backup_emp BEFORE DELETE ON EMP FOR EACH ROW
BEGIN
    INSERT INTO NEWEMP (EMP_ID,EMP_NAME,JOB,SALARY,DEPT_ID,DELETED_DATE) VALUES (:OLD.EMP_ID, :OLD.EMP_NAME, :OLD.JOB, :OLD.SALARY, :OLD.DEPT_ID, SYSDATE);
END;
/

-- SET SERVEROUTPUT ON;
-- @ E:\BARAIYA_ANIL\ASSIGNMENT_4\Q5_Backup_Data.sql

-- CREATE TABLE EMP
-- (
--     EMP_ID NUMBER(5) PRIMARY KEY,
--     EMP_NAME VARCHAR2(50),
--     JOB VARCHAR2(30),
--     SALARY NUMBER(8,2),
--     DEPT_ID NUMBER(4)
-- );

-- CREATE TABLE NEWEMP
-- (
--     EMP_ID NUMBER(5),
--     EMP_NAME VARCHAR2(50),
--     JOB VARCHAR2(30),
--     SALARY NUMBER(8,2),
--     DEPT_ID NUMBER(4),
--     DELETED_DATE DATE
-- );

-- INSERT INTO EMP (EMP_ID, EMP_NAME, JOB, SALARY, DEPT_ID) VALUES (101, 'Amit', 'CLERK', 2500, 10);
-- INSERT INTO EMP (EMP_ID, EMP_NAME, JOB, SALARY, DEPT_ID) VALUES (102, 'Priya', 'MANAGER', 5000, 20);
-- SELECT * FROM EMP; 

-- DELETE FROM EMP WHERE EMP_ID = 101;
-- SELECT * FROM NEWEMP;