-- SET SERVEROUTPUT ON;
-- @ E:\BARAIYA_ANIL\Q3_Print_1_To_50.sql
DECLARE
	Num NUMBER(3);
BEGIN
 -- FOR Num IN REVERSE 1..50
	FOR Num IN 1..50
	LOOP
		DBMS_OUTPUT.PUT_LINE(Num);
	END LOOP;
END;
/