-- SET SERVEROUTPUT ON;
-- @ E:\BARAIYA_ANIL\Q5_Even_1_To_50.sql
DECLARE
	Num NUMBER(3);
BEGIN
	DBMS_OUTPUT.PUT_LINE('Even Numbers : ');
	FOR Num IN 1..50
	LOOP
		IF MOD(Num,2) = 0 THEN
		DBMS_OUTPUT.PUT_LINE(Num);
		END IF;
	END LOOP;
END;
/